const dictionary={
'Settings':'设置','Done':'完成','Garage':'车库','Controls':'操控','Sound & display':'声音与画面','Driver':'车手','Bay Circuit':'晴湾赛道','Jade Citadel':'玉城古道','Race mode':'比赛模式','Your team':'你的队伍','Your kart':'你的赛车','Team Race':'组队赛','Solo Race':'个人赛','Blue Tide':'蓝潮车队','Red Rush':'赤焰车队','Car specifications':'车辆参数','Launch race':'开始比赛','RACE CONFIGURATION':'赛事准备','Your next escape.':'下一站，出发。','LIVE 3D / YOUR MACHINE':'实时 3D / 你的座驾','PRECISION. POWER. PRESENCE.':'精准操控，尽情驰骋。','SEASON 02 / THE NIGHT SHIFT':'第二赛季 / 逐风之旅','BUILT TO':'生而','BREAK AWAY.':'疾驰。','Six machines. Two worlds. One racing instinct.':'六款赛车，两条赛道，尽情驾驭。','01 / COASTLINE':'01 / 阳光海湾','02 / ANCIENT CHINA':'02 / 古城风光','4 VS 4 · TEAM POINTS':'4 对 4 · 队伍积分','8 RACERS · ONE WINNER':'8 位车手 · 争夺冠军','YOU + 3 AI':'你 + 3 位 AI','Local race · You + 7 AI · Auto throttle on by default':'本地比赛 · 你与 7 位 AI · 默认自动油门','55-second driving lesson':'55 秒驾驶教学','Replay driving lesson':'重新练习驾驶','Beginner assists':'新手辅助','Lower speed and smoother steering. You still steer every corner.':'降低速度，平滑转向。每个弯道仍需自己操控。','Personal best ghost':'个人最佳幽灵车','Livery':'涂装','Factory':'原厂','Medal gold (earn Bronze)':'奖牌金（获得铜牌解锁）','Solo mode only; teams keep their colors.':'仅个人赛使用；组队赛保留队伍颜色。','Auto-accelerate':'自动油门','Acceleration only. You must steer.':'只控制油门，转向由你掌控。','Engine & race sounds':'启用比赛声音','Toggle drift key (tap SPACE twice)':'切换式漂移（按空格开始，再按结束）','Reduced camera motion':'减少镜头运动','Graphics':'画质','Quality':'高画质','Performance':'流畅','Music':'音乐','Engine':'引擎','Prompts':'提示音','Keyboard or mobile touch controls. Settings save on this device.':'支持键盘和手机触控，设置保存在此设备。',
'LAP':'圈数','SECTOR':'分段','RACE TIME':'用时','POSITION':'名次','LIVE POINTS':'实时积分','BLUE':'蓝队','RED':'红队','SPEED':'速度','SHIELD':'护盾','YOUR KART':'你的赛车','SHIFT · NITRO STOCK':'SHIFT · 氮气储备','Q · EMP · NO FRIENDLY FIRE':'Q · EMP · 不伤队友','H · PAUSE / HELP':'H · 暂停 / 帮助','PIT STOP':'维修站','Take a breather.':'休息一下。','Resume race ↗':'继续比赛 ↗','Recover car to track':'返回赛道','Back to lobby':'返回大厅','Back to lobby / Change team':'返回大厅 / 更换队伍','Race again ↗':'再跑一局 ↗','Race complete':'比赛结束','CHEQUERED FLAG / FINAL RESULTS':'冲线 / 最终成绩','Place':'名次','Racer':'车手','Finish time':'完赛用时','Points':'积分','Skip lesson':'跳过教学','Try again':'再试一次','STEERING':'方向','LEFT':'左','RIGHT':'右','BRAKE / REV':'刹车 / 倒车','GO':'油门','AUTO THROTTLE':'自动油门','MINI':'小喷','NITRO':'氮气','DRIFT':'漂移','READY':'就绪','WAIT FOR WINDOW':'等待时机','HOLD TO SLIDE':'按住漂移','BOOST ACTIVE':'加速中','CENTER TILT':'校准倾斜','↻ Rotate your phone for a wider view':'↻ 横屏游玩，视野更宽','PHONE CONTROLS':'手机操控','Fullscreen / landscape ↗':'全屏 / 横屏 ↗','Play sideways for the best view.':'横屏游玩可获得更好的视野。','Enable tilt steering':'启用陀螺仪转向','Center steering':'校准方向','Optional: steer by tilting your phone. Touch arrows always override tilt.':'可选：倾斜手机转向。触控方向键始终优先。',
'BAY CIRCUIT / COASTAL GRAND PRIX':'晴湾赛道 / 海岸大奖赛','JADE CITADEL / ANCIENT WALL RUN':'玉城古道 / 城墙竞速','BAY CIRCUIT / LIVE MAP':'晴湾赛道 / 实时地图','JADE CITADEL / LIVE MAP':'玉城古道 / 实时地图','4V4 AI TEAM RACE':'4 对 4 AI 组队赛','SOLO / 7 AI RIVALS':'个人赛 / 7 位 AI 对手','EXIT BOOST':'出弯小喷','CUT BOOST':'脱喷','AIR BOOST':'飞喷','LAND BOOST':'落地喷','MINI TURBO':'小喷加速','NITRO BOOST':'氮气加速','TURBO':'加速','DRIFT / CHARGING':'漂移 / 蓄力中','RELEASE → E':'松开 → E','CHARGE → RELEASE → E':'蓄力 → 松开 → E','HOLD SPACE + STEER':'空格 + 方向键','HOLD DRIFT + STEER':'按住漂移 + 转向','SUPER TURBO READY':'强力小喷已蓄满','TURBO READY':'小喷已蓄满','FINISHED / AWAITING RESULTS':'已完赛 / 等待成绩','NITRO ENGAGED':'氮气启动','BOOST OVERCHARGE':'获得氮气','PHASE SHIELD':'护盾充满','EMP ARMED':'EMP 已充能','FINAL LAP':'最后一圈','LAP 2':'第二圈','FINISH / WAITING FOR RACERS':'已冲线 / 等待其他车手','GO! / FULL THROTTLE':'出发！全速前进','YOU WIN!':'你赢了！','BLUE TEAM WINS':'蓝队获胜','RED TEAM WINS':'红队获胜','DRAW':'平局','FINISH':'完赛','YOU':'你','TEAMMATE':'队友','RIVAL':'对手','DNF':'未完赛','PERSONAL BEST':'个人最佳','NEW PERSONAL BEST':'刷新个人最佳','PRACTICE COMPLETE':'教学完成','STEP COMPLETE':'完成！','TURN LEFT / RIGHT':'向左或向右转向','BRAKE TO SLOW DOWN':'踩刹车减速','CHARGE A DRIFT':'漂移蓄力','RELEASE, THEN PRESS E':'松开漂移，再按 E','Use A / D or touch arrows.':'使用 A / D 或触屏方向键。','Hold S or BRAKE until speed drops.':'按住 S 或刹车键，直到车速降低。','Hold SPACE / DRIFT with steering until the bar turns blue.':'按住空格或漂移键并转向，直到蓄力条变蓝。','Release SPACE / DRIFT, then press E / MINI while ready.':'松开空格或漂移键，趁就绪时按 E 或小喷键。','Practice paused. Retry or skip to race.':'练习已暂停，可重试或跳过进入比赛。','MEDAL GOLD UNLOCKED':'奖牌金涂装已解锁','Finish a race to earn Bronze.':'完成比赛获得铜牌。','Release a charged drift, then press E for a mini turbo.':'松开已蓄力的漂移，再按 E 触发小喷。','Release charged drift, then press E':'松开已蓄力的漂移，再按 E','Release drift, then press E to boost':'松开漂移，再按 E 小喷','Tap SPACE again, then press E':'再按空格结束漂移，然后按 E','Turbo ready · Keep charging to upgrade':'小喷已蓄满 · 继续蓄力可升级','Super turbo ready · Release SPACE':'强力小喷已蓄满 · 松开空格再按 E','Super turbo ready · Tap SPACE':'强力小喷已蓄满 · 再按空格再按 E',
'W / ↑ to accelerate, S / ↓ to brake / reverse, A / D or ← / → to steer.':'W / ↑ 加速，S / ↓ 刹车或倒车，A / D 或 ← / → 转向。','Press H at any time to pause or resume.':'随时按 H 暂停或继续。','Trigger a ready boost: release a charged drift, jump a gold ramp, or land. Each window is brief.':'蓄力漂移结束、驶离金色跳台或落地后，按 E 或小喷键触发；时机短暂。','Drift through a corner':'在弯道中漂移','Use 1 nitro charge':'消耗一格氮气','Disrupt nearby opponents':'干扰范围内的对手','Restart the entire race':'重新开始整场比赛','Points by position: 15 / 12 / 10 / 8 / 6 / 4 / 2 / 1.':'名次积分：15 / 12 / 10 / 8 / 6 / 4 / 2 / 1。','Racing ends 20 seconds after the first finish. DNF racers score zero; equal team scores result in a draw.':'首位车手完赛后 20 秒结算。未完赛得零分；队伍同分为平局。'
};
Object.assign(dictionary,{
'Bronze: finish. Silver: finish with ≤3 collisions. Gold: also complete 6 drifts and 6 mini boosts.':'铜牌：完赛。银牌：完赛且碰撞不超过 3 次。金牌：同时完成 6 次漂移和 6 次小喷。',
'Auto-accelerate is recommended. Hold arrows to steer and DRIFT to slide; release DRIFT, then tap MINI for a boost.':'推荐自动油门。按方向键转向，按住漂移键滑行；松开漂移后点击小喷。',
'At speed, hold':'达到速度后，按住','Keep SPACE held while countersteering. Release, then press E for a mini turbo.':'反打方向时保持空格；松开后按 E 小喷。','E / MINI: exit, air and landing boosts. Three gold ramps per lap.':'E / 小喷键：出弯小喷、飞喷和落地喷。每圈有三处金色跳台。','Keyboard: W accelerate · S brake / reverse · A / D steer · Shift nitro · Q EMP.':'键盘：W 油门 · S 刹车或倒车 · A / D 转向 · Shift 氮气 · Q EMP。','Hold S or BRAKE at rest to reverse. Brake overrides auto throttle. Pause to recover if stuck.':'停车后按住 S 或刹车键倒车。刹车优先于自动油门，卡住时可暂停并返回赛道。',
'Lightweight and responsive. Built for quick direction changes.':'轻巧灵活，适合快速改变方向。','Balanced speed and handling. A great kart for your first race.':'速度与操控均衡，适合初次参赛。','High top speed and a wide body. Plan your corner entries early.':'高速宽体赛车，入弯需要提前规划。','Low body kit and a double rear wing. Drift charges 40% faster than APEX.':'低车身搭配双层尾翼，漂移蓄力比 APEX 快 40%。','Wide-track armored buggy. Deep-tread tires, independent suspension, open intake stacks and a reinforced cockpit.':'宽轮距装甲越野车，搭配深纹轮胎、独立悬挂、进气管和加固座舱。','Round headlights and a chrome grille. Quick acceleration with a lower top speed.':'圆形车灯和镀铬格栅，起步轻快，极速较低。','Speed':'极速','Accel.':'加速','Handling':'操控','Drift':'漂移','RELEASE → MINI':'松开 → 小喷','CHARGING':'蓄力中','TAP TO BOOST':'点击加速','DRIFT TO FILL':'漂移充能','DRIVER PROFILE':'车手档案','DRAG TO ROTATE':'拖动旋转','STANDING BY':'待命','Stand':'站立','♫ Dance':'♫ 跳舞','★ Victory':'★ 胜利','PIT GARAGE':'维修车库','↝ DRIFT TIP':'↝ 漂移提示',
'Back to race ↗':'返回比赛 ↗','ENGINEERED FOR THE OUTSIDE LINE':'为突破而生','01 / ARMORED SERIES':'01 / 装甲系列','Overview':'概览','Front':'正面','Side':'侧面','Rear':'背面','Top':'顶部','DRAG TO ORBIT':'拖动旋转','SCROLL TO ZOOM':'滚动缩放','ARROW KEYS TO ROTATE':'方向键旋转','HEAVYWEIGHT. LIGHT ON ITS FEET.':'重装上阵，灵活驾驭。','Built to':'生而','take the line.':'竞速。','A wide-track machine with layered armor, exposed suspension and an unmistakable mechanical silhouette.':'宽轮距赛车，层叠装甲与外露悬挂，展现鲜明机械轮廓。','CHASSIS':'底盘','Reinforced spaceframe':'加固空间车架','SUSPENSION':'悬挂','Independent double wishbone':'独立双叉臂','WHEELS':'车轮','Deep-tread / six-spoke alloy':'深纹轮胎 / 六辐合金轮毂','POWERTRAIN':'动力布局','Rear-mounted / twin exhaust':'后置 / 双排气','Auto rotate':'自动旋转','Show driver':'显示车手','Wireframe':'线框','Take it to the circuit ↗':'驾驶它去参赛 ↗','Original procedural vehicle inspired by the supplied racing reference. Every angle is rendered in 3D.':'参考赛车造型设计的原创程序化模型，支持完整 3D 视角。'});
let language='en';try{language=localStorage.getItem('apex-language')||(navigator.language.startsWith('zh')?'zh':'en');}catch{}
export function tr(text){if(language!=='zh')return text;const s=text.trim();if(dictionary[s])return text.replace(s,dictionary[s]);
 return text.replace(/Armored buggy|Lightweight|All-rounder|Speedster|Drift specialist|Classic/g,x=>({'Armored buggy':'装甲越野车',Lightweight:'轻量型','All-rounder':'全能型',Speedster:'极速型','Drift specialist':'漂移专家',Classic:'经典型'}[x])).replace(/EXIT BOOST|CUT BOOST|AIR BOOST|LAND BOOST|PERSONAL BEST|NEW PERSONAL BEST|TEAMMATE|RIVAL|READY|FINISH|WAIT FOR WINDOW/g,x=>dictionary[x]||x).replace(/PRESS E/g,'按 E').replace(/TAP MINI/g,'点击小喷').replace(/CHAIN /g,'连喷 ').replace(/EMP: (\d+) TARGETS/g,'EMP：$1 位对手在范围内').replace(/COOLDOWN ([\d.]+)s/g,'冷却 $1 秒').replace(/EMP HIT: (\d+)/g,'EMP 命中：$1').replace(/NO TARGETS/g,'范围内无对手').replace(/LAP BEST/g,'最佳圈速').replace(/SECTOR ([1-6])/g,'分段 $1').replace(/BRAKE · /g,'减速 · ').replace(/LEFT TURN/g,'左弯').replace(/RIGHT TURN/g,'右弯').replace(/GOLD/g,'金牌').replace(/SILVER/g,'银牌').replace(/BRONZE/g,'铜牌').replace(/Collisions/g,'碰撞').replace(/Drifts/g,'漂移').replace(/Mini boosts/g,'小喷').replace(/Best medal/g,'最佳奖牌').replace(/Recovery avg/g,'平均脱困用时').replace(/Your position: P/g,'你的名次：P').replace(/Points awarded to finishers/g,'完赛车手获得积分').replace(/3 laps/g,'3 圈').replace(/Waiting for racers/g,'等待其他车手').replace(/remaining/g,'剩余');
}
export function setupLanguage(){
 const select=document.querySelector('#languageSetting');if(select)select.value=language;
 const originals=new WeakMap(),translated=new WeakMap();
 function visit(node){if(node.nodeType===3){const current=node.nodeValue;if(current===translated.get(node))return;const source=originals.get(node);const raw=current===source?source:current;originals.set(node,raw);const next=tr(raw);translated.set(node,next);if(next!==current)node.nodeValue=next;}else if(node.nodeType===1&&!['SCRIPT','STYLE','CANVAS'].includes(node.tagName)){for(const child of node.childNodes)visit(child);}}
 visit(document.body);document.documentElement.lang=language==='zh'?'zh-CN':'en';
 const observer=new MutationObserver(records=>{for(const r of records){if(r.type==='characterData')visit(r.target);else for(const n of r.addedNodes)visit(n);}});observer.observe(document.body,{subtree:true,childList:true,characterData:true});
 select?.addEventListener('change',()=>{try{localStorage.setItem('apex-language',select.value);}catch{}location.reload();});
}
